
scroll_offset = 4
[keybindings.Explorer]
"<q>" = "Quit"  # Quit the application
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<2>" = { SwitchTo = "TodoList" }
"<3>" = { SwitchTo = "Inspector" }
"f" = "ToggleShowFinished"
"x" = "Delete"
"t" = "NewTask"
"g" = "NewSubGroup"
"<Shift-g>" = "NewGroup"
"j" = "MoveDown"
"k" = "MoveUp"
"<Ctrl-d>" = "MovePageDown"
"<Ctrl-u>" = "MovePageUp"

"l" = "MoveInto"
"h" = "MoveOutOf"

[keybindings.TodoList]
"<q>" = "Quit"  # Quit the application
"<Ctrl-d>" = "Quit"  # Another way to quit
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<1>" = { SwitchTo = "Explorer" }
"<3>" = { SwitchTo = "Inspector" }
"j" = "MoveDown"
"k" = "MoveUp"
"f" = "ToggleFinishTask"

[keybindings.Inspector]
"<q>" = "Quit"  # Quit the application
"<Ctrl-d>" = "Quit"  # Another way to quit
"<Ctrl-c>" = "Quit"  # Yet another way to quit
"<Ctrl-z>" = "Suspend"  # Suspend the application
"<1>" = { SwitchTo = "Explorer" }
"<2>" = { SwitchTo = "TodoList" }
"r" = "RandomColor"
"n" = "EditName"
"c" = "EditColor"
"p" = "EditPriority"
"u" = "EditDue"
"d" = "EditDescription"
"f" = "ToggleFinishTask"
"t" = "NewTask"
"g" = "NewSubGroup"



[providers.recurring]
interval = "30d"
