[package]
name = "providers"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {workspace=true}
toml = "0.9.8"
once_cell = "1.21.3"
inventory = "0.3.21"
color-eyre = "0.6.5"
serde = "1.0.228"
chrono = "0.4.42"
